// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type GetTasksResponse struct {
	Data []*Task `json:"data"`
	Meta *Meta   `json:"meta"`
}

type Meta struct {
	TotalTasks int32 `json:"total_tasks"`
}

type Query struct {
}

type SubTask struct {
	TaskID      string     `json:"task_id"`
	Name        string     `json:"name"`
	Description *string    `json:"description,omitempty"`
	Status      string     `json:"status"`
	StartTime   *time.Time `json:"start_time,omitempty"`
	EndTime     *time.Time `json:"end_time,omitempty"`
	UpdatedUser string     `json:"updated_user"`
	TaskOrder   int32      `json:"task_order"`
	TaskType    *TaskType  `json:"task_type"`
}

type Task struct {
	TaskID      string     `json:"task_id"`
	Name        string     `json:"name"`
	Description *string    `json:"description,omitempty"`
	Status      string     `json:"status"`
	StartTime   *time.Time `json:"start_time,omitempty"`
	EndTime     *time.Time `json:"end_time,omitempty"`
	UpdatedUser string     `json:"updated_user"`
	Subtasks    []*SubTask `json:"subtasks,omitempty"`
}

type TaskType struct {
	Task       string  `json:"task"`
	RedjadeURL *string `json:"redjade_url,omitempty"`
	SurveyID   *string `json:"survey_id,omitempty"`
}
