// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type RedjadeTask struct {
	RedjadeTaskID int32
	TaskTypeID    int32
	RedjadeLink   pgtype.Text
}

type SamsSurveyTask struct {
	TaskID     int32
	TaskTypeID int32
	SurveyID   pgtype.Text
}

type Task struct {
	TaskID              pgtype.UUID
	ParentTaskID        pgtype.UUID
	TaskOrder           int32
	Name                string
	Description         pgtype.Text
	StartTime           pgtype.Timestamp
	EndTime             pgtype.Timestamp
	StatusID            int32
	UpdatedTs           pgtype.Timestamp
	UpdatedUser         string
	LastModifiedProcess pgtype.Text
	LastModifiedApp     pgtype.Text
	LastRequestID       string
	LastActionID        pgtype.Text
}

type TaskKeyword struct {
	KeywordID int32
	TaskID    pgtype.UUID
	Keyword   string
}

type TaskStatus struct {
	StatusID   int32
	StatusName string
}

type TaskType struct {
	TaskTypeID int32
	TaskID     pgtype.UUID
	Type       string
}
